# Generated by Django 3.0.8 on 2020-07-22 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 10, 46, 36, 787935)),
        ),
        migrations.AlterField(
            model_name='post',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 23, 10, 46, 36, 787935)),
        ),
    ]
